# Generated by Django 2.0.6 on 2018-07-02 23:03

import admin_readonly_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_json', admin_readonly_fields.fields.ReadOnlyJsonField()),
                ('content_md', admin_readonly_fields.fields.ReadOnlyMarkdownField()),
            ],
        ),
    ]
